<a href="https://colab.research.google.com/github/merve-karagoz/ml_projects/blob/main/math_for_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# devrik matris oluşturma:
A = np.array(range(12)).reshape(4,3) # 4*3 lük matris
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
A.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [ ]:
# matrislerde toplama ve çıkarma işlemi:
m = np.random.randint(20, size=(5, 3))
m

array([[ 0,  2,  1],
       [ 2,  0, 12],
       [12, 12,  0],
       [ 4,  2,  0],
       [11, 14, 19]])

In [ ]:
m2 = np.random.randint(5, size=(5, 3))
m2

array([[2, 0, 2],
       [2, 0, 2],
       [4, 3, 0],
       [3, 0, 2],
       [3, 4, 0]])

In [ ]:
m + m2

array([[ 2,  2,  3],
       [ 4,  0, 14],
       [16, 15,  0],
       [ 7,  2,  2],
       [14, 18, 19]])

In [ ]:
m - m2

array([[-2,  2, -1],
       [ 0,  0, 10],
       [ 8,  9,  0],
       [ 1,  2, -2],
       [ 8, 10, 19]])

In [ ]:
# matrisin tersi
from numpy.random import RandomState
rnd=RandomState(42)
n=4
A=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        A[i,j]=rnd.randint(0,3)

A_inv=np.linalg.inv(A)
print("A:\n",A,end="\n\n")
print("A matrisin tersi A^-1:\n",A,end="\n\n")
print("A matrisinin tersiyle çarpımı A.A^-1:\n",A.dot(A_inv))

A:
 [[2. 0. 2. 2.]
 [0. 0. 2. 1.]
 [2. 2. 2. 2.]
 [0. 2. 1. 0.]]

A matrisin tersi A^-1:
 [[2. 0. 2. 2.]
 [0. 0. 2. 1.]
 [2. 2. 2. 2.]
 [0. 2. 1. 0.]]

A matrisinin tersiyle çarpımı A.A^-1:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# dot çapraz çarpım
a=np.array([3, 9, 7])
b=np.array([4, 6, 3])

c=a*b
a_dot_b= np.sum(c)

print("a   :", a)
print("b   :", b)
print("a.b :", a_dot_b)

a   : [3 9 7]
b   : [4 6 3]
a.b : 87


In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [ ]:
# determinant
rnd=RandomState(24)
n=4
A=np.zeros((n,n))
for i in range(n):
    for j in range(n):
            A[i,j]=rnd.randint(0,3)

A_det=np.linalg.det(A)           
print("A:\n",A,end="\n\n")
print("A matrisinin determinantı:",A_det)

A:
 [[2. 0. 1. 1.]
 [1. 0. 0. 2.]
 [1. 2. 1. 1.]
 [0. 0. 2. 0.]]

A matrisinin determinantı: 11.999999999999995


In [ ]:
a = np.array([[1,2], [3,4]]) 
print(np.linalg.det(a))

-2.0000000000000004


In [ ]:
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print(b) 
print(np.linalg.det(b))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0


In [ ]:
# broadcasting
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0 ])
a*b

array([2., 4., 6.])

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a*b

array([2., 4., 6.])

In [ ]:
a = np.array([3, 9, 7])
b = np.array([4, 6, 3])

c = a * b
a_dot_b = np.sum(c)

print("a  :", a)
print("b  :", b)
print("a.b:", a_dot_b)

a  : [3 9 7]
b  : [4 6 3]
a.b: 87


In [ ]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[3, 1, 1], [-1, 3, 1]])
print("A=",A)
# SVD
U, S, V_T = svd(A)
# left singular vectors
print("U=")
print(U)
# singular values
print("S=")
print(S)
#right singular vectors
print("V_T=")
print(V_T)

A= [[ 3  1  1]
 [-1  3  1]]
U=
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
S=
[3.46410162 3.16227766]
V_T=
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.26260748e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [ ]:
# Creating S diagonal matrix
S_diag = array([[3.46410162, 0, 0], [0, 3.16227766, 0]])
S_diag

array([[3.46410162, 0.        , 0.        ],
       [0.        , 3.16227766, 0.        ]])

In [ ]:
B = U.dot(S_diag.dot(V_T))
print("Reconstructed matrix:")
print(B)

Reconstructed matrix:
[[ 3.  1.  1.]
 [-1.  3.  1.]]


In [ ]:
# simetrik matris ayrışımı
n = 3
A=np.zeros((n,n),dtype=np.int32)
for i in range(n):
    for j in range(n):
      A[i,j]=np.random.randint(1,10)

egienvalues, egienvectors=np.linalg.eig(A)

print("öz değerler:\n",egienvalues,end="\n\n")
print("öz vektörler matrisi:\n",egienvectors,end="\n\n")
for i, egienvector in enumerate(egienvectors.T):
    print("{}.öz vektör:{}".format(i+1,egienvector))

öz değerler:
 [11.41869517  2.07026403  3.5110408 ]

öz vektörler matrisi:
 [[-0.7109633  -0.54238076  0.25988498]
 [-0.40558386 -0.69557653 -0.96418998]
 [-0.57448492  0.47116495  0.05289115]]

1.öz vektör:[-0.7109633  -0.40558386 -0.57448492]
2.öz vektör:[-0.54238076 -0.69557653  0.47116495]
3.öz vektör:[ 0.25988498 -0.96418998  0.05289115]


In [ ]:
n=1
print("egienvectors[:,{}]*egienvalues[{}]:{}".format(
    n,
    n,
    egienvectors[:,n]*egienvalues[n])
)
print("A.dot(egienvectors[:,{}]           :{}".format(n,A.dot(egienvectors[:,n])))

egienvectors[:,1]*egienvalues[1]:[ 1.03044527-1.10513357j -1.57958923-0.41346002j -0.00932755+2.31556228j]
A.dot(egienvectors[:,1]           :[ 1.03044527-1.10513357j -1.57958923-0.41346002j -0.00932755+2.31556228j]


In [ ]:
LAMBDA=np.diag(egienvalues)
print("A:\n", A,end="\n\n")
print("Q:\n", egienvector,end="\n\n")
print("LAMBDA:\n", LAMBDA,end="\n\n")
print("Q^-1:\n",np.linalg.inv(egienvectors),end="\n\n")
print("Q.LAMBDA.Q^-1:\n",egienvectors.dot(LAMBDA).dot(np.linalg.inv(egienvectors)))

A:
 [[6 1 6]
 [1 4 4]
 [3 1 7]]

Q:
 [ 0.25988498 -0.96418998  0.05289115]

LAMBDA:
 [[11.41869517  0.          0.        ]
 [ 0.          2.07026403  0.        ]
 [ 0.          0.          3.5110408 ]]

Q^-1:
 [[-0.54761025 -0.19823473 -0.92303276]
 [-0.75466687 -0.14650459  1.03738204]
 [ 0.77477515 -0.8480632  -0.36010684]]

Q.LAMBDA.Q^-1:
 [[6. 1. 6.]
 [1. 4. 4.]
 [3. 1. 7.]]


In [ ]:
# Cholesky Ayrıştırma 
import pprint
import scipy
import scipy.linalg # SciPy Linear Algebra Library

A = scipy.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])
L = scipy.linalg.cholesky(A, lower=True)
U = scipy.linalg.cholesky(A, lower=False)

print("A:")
pprint.pprint(A)

print("L:")
pprint.pprint(L)


print("U:")
pprint.pprint(U)



A:
array([[ 6,  3,  4,  8],
       [ 3,  6,  5,  1],
       [ 4,  5, 10,  7],
       [ 8,  1,  7, 25]])
L:
array([[ 2.44948974,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  2.12132034,  0.        ,  0.        ],
       [ 1.63299316,  1.41421356,  2.30940108,  0.        ],
       [ 3.26598632, -1.41421356,  1.58771324,  3.13249102]])
U:
array([[ 2.44948974,  1.22474487,  1.63299316,  3.26598632],
       [ 0.        ,  2.12132034,  1.41421356, -1.41421356],
       [ 0.        ,  0.        ,  2.30940108,  1.58771324],
       [ 0.        ,  0.        ,  0.        ,  3.13249102]])


<ipython-input-6-1fe63bf5b49f>:6: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  A = scipy.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])


In [ ]:
''' A'nın bir Cholesky ayrıştırmasını gerçekleştirir, ki bu simetrik ve pozitif tanımlı bir matris olsun. 
İşlev alt değişken üçgen matrisi L'yi döndürür.'''

In [ ]:
from math import sqrt
from pprint import pprint

def cholesky(A):
    n = len(A)
    
# L için sıfır matrisi oluşturmak
    L = [[0.0] * n for i in range(n)]

# Cholesky ayrıştırmasını gerçekleştirme
    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))

            if(i == k): # çapraz elemanlar
               L[i][k] = sqrt(A[i][i] - tmp_sum)

            else:
               L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))

    return L

A = [[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]]
L = cholesky(A)

print("A:")
pprint(A)

print("L:")
pprint(L)

print("U:")
pprint(U)





A:
[[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]]
L:
[[2.449489742783178, 0.0, 0.0, 0.0],
 [1.2247448713915892, 2.1213203435596424, 0.0, 0.0],
 [1.6329931618554523, 1.414213562373095, 2.309401076758503, 0.0],
 [3.2659863237109046,
  -1.4142135623730956,
  1.5877132402714704,
  3.1324910215354165]]
U:
array([[ 2.44948974,  1.22474487,  1.63299316,  3.26598632],
       [ 0.        ,  2.12132034,  1.41421356, -1.41421356],
       [ 0.        ,  0.        ,  2.30940108,  1.58771324],
       [ 0.        ,  0.        ,  0.        ,  3.13249102]])


In [ ]:
# Vektör Normları
a = np.array([1, -2, 4, -5, 1, -8, 7, -2])
l1 = np.sum(np.absolute(a))
l2 = np.sqrt(np.sum(a ** 2))
max_norm = np.max(np.abs(a))
min_norm = np.min(np.abs(a))
frobenius_norm = np.sqrt(np.sum(a ** 2))

print("a    :", a)
print("l1 norm:", l1.astype(np.float32))
print("l2 norm:{:.2f}".format(l2))
print("max norm:", max_norm.astype(np.float32))
print("min norm:", min_norm.astype(np.float32))
print("frobenius norm:{:.2f}".format(frobenius_norm))



a    : [ 1 -2  4 -5  1 -8  7 -2]
l1 norm: 30.0
l2 norm:12.81
max norm: 8.0
min norm: 1.0
frobenius norm:12.81


In [ ]:
# numpy.linalg.norm
import math
l1 = np.linalg.norm(a, ord=1)
l2 = np.linalg.norm(a, ord=2)
max_norm = np.linalg.norm(a, ord=math.inf)
min_norm = np.linalg.norm(a, ord=math.inf)
frobenius_norm = np.linalg.norm(a, ord=None)

print("a    :", a)
print("l1 norm:", l1.astype(np.float32))
print("l2 norm:{:.2f}".format(l2))
print("max norm:", max_norm.astype(np.float32))
print("min norm:", min_norm.astype(np.float32))
print("frobenius norm:{:.2f}".format(frobenius_norm))

a    : [ 1 -2  4 -5  1 -8  7 -2]
l1 norm: 30.0
l2 norm:12.81
max norm: 8.0
min norm: 8.0
frobenius norm:12.81
